services:
  - type: web
    name: mutant-detector-api
    env: docker
    dockerfilePath: ./Dockerfile
    # buildCommand/startCommand are ignored for docker, but harmless if left
    buildCommand: ./mvnw.cmd -B clean package -DskipTests
    startCommand: java -Dserver.port=$PORT -jar target/MercadoLibre-1.0-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: "8080"
      - key: JAVA_VERSION
        value: "17"
