services:
  - type: web
    name: mutant-detector-api
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: "8080"
      - key: JAVA_VERSION
        value: "17"
    healthCheckPath: /swagger-ui.html
